name: Filter TR EPG Python

on:
  schedule:
    - cron: '0 */12 * * *'  # Her 12 saatte bir
  workflow_dispatch:

jobs:
  filter-tr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Download & Filter TR EPG
        run: python filter_tr_epg.py

      - name: Commit & Push TR EPG
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add tr-epg.xml
          git commit -m "Update TR EPG" || echo "No changes"
          git push
