name: Filter TR EPG

on:
  schedule:
    - cron: '0 */12 * * *'  # Her 12 saatte bir
  workflow_dispatch:

jobs:
  filter-tr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Download & Filter TR EPG
        run: node filterTrEpg.js

      - name: Commit & Push TR EPG
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add tr-epg.xml
          git commit -m "Update TR EPG" || echo "No changes"
          git push
